{% set name = "ps2ff" %}
{% set version = "1.5.9" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ps2ff-{{ version }}.tar.gz
  sha256: 9ec9af186a4f69ec5bf46f9350dd323ef4bdba0d050b7270aecbc648971ab78a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - run_ps2ff = ps2ff.bin.run_ps2ff:cli
    - run_ps2ff_single_event = ps2ff.bin.run_ps2ff_single_event:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
    - wheel
  run:
    - python >={{ python_min }}
    - configobj >=5.0.6
    - numpy >=1.21,<2.0
    - scipy >=1.7
    - pandas >=1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ps2ff
  commands:
    - run_ps2ff --help
    - run_ps2ff_single_event --help

about:
  home: https://code.usgs.gov/ghsc/esi/ps2ff
  license: LicenseRef-PublicDomain
  summary: 'Produce approximated earthquake rupture distances from point source information.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
    - ocefpaf
