{% set version = "1.5.1" %}

package:
  name: ps2ff
  version: {{ version }}

source:
  url: https://github.com/usgs/ps2ff/archive/v{{ version }}.tar.gz
  sha256: 423d670ee7f5619fff3d8ae1e8e7369fda17dfe1cecb66e095617a378d44e29f

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - configobj
    - impactutils

test:

  imports:
    - ps2ff

about:
  home: https://github.com/usgs/ps2ff
  license: Public Domain
  summary: 'Produce approximated earthquake rupture distances from point source information.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
