appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WJOXLikJd+REF2wVtNc5/nT08gQ/sdF/gl01fWH5KujYr0oKhPynxY03lalQNlb6FXef/wOPa/YJ3jbF0HDR5slp2ivWlSWCVSvSNm2ehk107mIMdwwq7ZTP5GZDdXVnezo58gkvhPkqalPVe8Fh9KUnaNwSnRVvQb2jPYSkUZbs9dLUydzNhg10Cx1qhJBk8OwUD/cVXDaffecYyPqEO/cRzS7GBcp7C/Pn+gDIL8Av2KnXHalNxm8Oc6t8LaORk726ruKMfOGcjC26K7K4vdC+HWTCXLrukNlaWu6Ed39ubES4GggAHhtp8UCteD9gE24BoyYBuunJujY5uhUa+l+nubo3uUHavTe+Mwi2X6d9h73Kk8aWQYs6e75iR/LWlmZEjdTI51TPHXcaMWWl9an1QaY4MCSPHFtXbjRGb5zEPGgK3FLallnyVV4Rnjr6anmzaui8NSeN1sRJ/UiMPnjzZnDjwy5DIUku+0/z5rYkoWBMKp9y3t5ih/9odvFOlidsNcSC2rH7T9nD7V3yyxv+gMMS0uldycQ9P8Kwz8SpGwfX1OnMht/FyBK1ZKO8/r9dj25I8GbKO76QrKT4l1yM2IZ7EsFMjaD2ERciLZNZY9aODZnxDH4Wu3o/stbQTFdmNx8KJPEnDZHA7q3fMnFYE1tXQFVC3a3QD8hl8y4=}
